### ISSUE TITLE
Migrating `language-graphql-lb` to here

### ISSUE THREAD

**Issue by asiandrummer** [rmosolgo/language-graphql#10]
As discussed with @gandm and @rmosolgo in [this issue](https://github.com/gandm/language-graphql-lb/issues/2), we should migrate to this repo and publish it to npm/apm. I think I can do the copy/paste myself, but I'd need some help publishing this to npm/apm I guess :)

Creating issue to track progress.

**Comment by rmosolgo** [comment]
0.8.0 on apm has syntax and tests from language-babel, thanks!
