### ISSUE TITLE
Unknown directive "connection"

### ISSUE THREAD

**Issue by steida** [rmosolgo/language-graphql#15]
`@connection(key: "Posts_allPosts") {` invokes error "Unknown directive "connection""

```jsx
export default createFragmentContainer(
  Posts,
  graphql`
    fragment Posts_viewer on Viewer {
      allPosts(first: $first, orderBy: createdAt_DESC)
        @connection(key: "Posts_allPosts") {
        edges {
          node {
            id
            ...Post_post
          }
        }
      }
      # To understand what's happening here:
      # Post_viewer fragment will be attached to viewer.__fragments for Post.js
      ...Post_viewer
    }
  `,
);
```

**Comment by rmosolgo** [comment]
Hi, I'm afraid I don't quite understand, could you take a screenshot of the error?

**Comment by steida** [comment]
![screen shot 2017-08-18 at 02 41 53](https://user-images.githubusercontent.com/66249/29439576-d93f8914-83be-11e7-8594-35c24da205dc.png)

**Comment by steida** [comment]
![screen shot 2017-08-18 at 02 42 01](https://user-images.githubusercontent.com/66249/29439580-dfe2c556-83be-11e7-97bb-0d5295170924.png)

**Comment by rmosolgo** [comment]
Interesting! This library (`language-graphql`) does syntax highlighting, but not validation. Are you using another library for validation?

**Comment by steida** [comment]
I didn't install anything, but I just realized it could come from https://nuclide.io/docs/languages/graphql/ probably.

**Comment by steida** [comment]
Ok, closing for now.
