### ISSUE TITLE
Is there a way to make this work for queries within jsx file?

### ISSUE THREAD

**Issue by oguzbilgic** [rmosolgo/language-graphql#2]

**Comment by rmosolgo** [comment]
It must be _possible_, I've seen context-mixin for HTML + Ruby with `.erb` files!

**Comment by devknoll** [comment]
@rmsologo Nope, not yet

**Comment by kachkaev** [comment]
@devknoll any plans on making it available at some point? Just did a quick search – looks like there're still no GraphQL highlighters for Atom. Looking forward to try GraphQL in Apollo+React stack.

**Comment by rmosolgo** [comment]
GraphQL is highlighted in `Relay.QL

**Comment by tonyxiao** [comment]
Could we get support for `gql` tag as well? https://github.com/apollostack/graphql-tools/issues/123

**Comment by rmosolgo** [comment]
Perhaps the `Relay.QL` PR can be an example for how it's done!

**Comment by tonyxiao** [comment]
https://github.com/atom/language-javascript/pull/429 Hopefully this works.

**Comment by rmosolgo** [comment]
Looks like this is supported in language-babel as well: 

![image](https://cloud.githubusercontent.com/assets/2231765/21264620/1a49e856-c36b-11e6-8e8c-ecdf0040b0e8.png)

![image](https://cloud.githubusercontent.com/assets/2231765/21264628/22802f94-c36b-11e6-98cc-54e87aa5798a.png)
