### ISSUE TITLE
Collaborating nuclide graphql language service

### ISSUE THREAD

**Issue by asiandrummer** [rmosolgo/language-graphql#8]
@rmosolgo - Apologies for opening an issue; I wanted to chat with you about us collaborating to develop Nuclide GraphQL language service, but couldn't find a viable contact information. Would you be interested in working together to provide Nuclide/Atom language service?

Let me know what you think!

**Comment by rmosolgo** [comment]
Yes, I'm definitely interested! I'm in the GraphQL slack, and I've also just put my email back on my GitHub profile if you prefer that. I saw your talk from a while back and it looks AMAZING!

**Comment by asiandrummer** [comment]
Closing in favor of #10
